import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import { Poppins, Inter } from 'next/font/google';
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ['latin'], // Define subsets (e.g., latin)
  weight: ['100', '200', '300', '400', '500', '600', '700'], // Specify font weights if needed
});

const inter = Inter({
  subsets: ['latin'], // Define subsets (e.g., latin)
  weight: ['100', '200', '300', '400', '500', '600', '700'], // Specify font weights if needed
});



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  navBg?: string; // navBg prop added
};

export default function RootLayout({ children, navBg }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Pass navBg dynamically */}
        <Header/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
